version: 2

project_name: ldoce-cli

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums_sha256.txt
  algorithm: sha256
